{% set version = "4.4.2" %}
package:
    name: pyolog
    version: {{ version }}

source:
    url: https://github.com/NSLS-II/pyOlog/archive/v{{ version }}.tar.gz
    fn: pyolog-v{{ version }}.tar.gz

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - setuptools
        - requests
        - keyring
        - six
        - ipython

# don't import pyolog because it looks for config info on import...
# test:
#   imports:
#         - pyOlog

about:
    home: http://olog.github.io/
    license: MIT
    summary: Python client for the OLog
