{% set name = "pyOlog" %}
{% set version = "4.4.3" %}
{% set sha256 = "b7530236ea8c6ae1f437aea66ef8ce6d2a8d7fca4d1456ecccd29ff842defd0b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Fix-defaults-for-username.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ipython
    - keyring
    - requests
    - six

test:
  imports:
    - pyOlog

about:
  home: http://olog.github.io/
  license: MIT
  license_file: LICENSE.md
  summary: Python client for the OLog
  dev_url: https://github.com/NSLS-II/pyOlog
