{% set name = "pyOlog" %}
{% set version = "4.4.2" %}
{% set sha256 = "c6094a3f9e47235dda2e3eb846762d614a5177443beb5b1243ca09fa435893d6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ipython
    - keyring
    - requests
    - six

test:
  imports:
    - {{ name }}

about:
  home: http://olog.github.io/
  license: MIT
  license_file: LICENSE.md
  summary: Python client for the OLog
  dev_url: https://github.com/NSLS-II/pyOlog
